print(3+4)
print(4-3)
print(3*4)
print(3%4)
print(3/4)
print(3**4)
print(3//4)

print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type(["Asabeneh","Python","Finland"]))
print(type([1, 2, 3]))
print(type({"name" : "Asabeneh"}))
print(type({3.5, 9.7, 1.6}))
print(type((3,5, 9.7, 1.6))) 
print(type(3 == 3))
print(type(3 >= 3))
print(type("Yaretzi Yashiri"))
print(type("Macías Herrera"))
print(type("México"))
